[project]
name = "blog-bmispelon-rocks"
version = "0.1.0"
description = "Blog engine and content for blog.bmispelon.rocks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "lxml>=6.0.0",
    "typer>=0.16.0",
]
